
package smarthomesystem;

public class DeviceControlPage extends javax.swing.JFrame {
    private MainController controller;
    
    public DeviceControlPage(MainController controller) {
        initComponents();
        this.controller = controller;
        setTitle("Device Control");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roomcbox = new javax.swing.JComboBox<>();
        deviceCbox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        valuelbl = new javax.swing.JLabel();
        valueSlider = new javax.swing.JSlider();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        viewStatusbtn = new javax.swing.JButton();
        backtohomebtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setBackground(new java.awt.Color(51, 204, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DEVICE CONTROL");
        jLabel1.setOpaque(true);

        jLabel2.setText("Device :");

        jLabel3.setText("Room :");

        roomcbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Living Room", "Bedroom", "Kitchen", "Office" }));
        roomcbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomcboxActionPerformed(evt);
            }
        });

        deviceCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Light", "Fan", "Tv", "Door", " " }));
        deviceCbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deviceCboxActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));

        valuelbl.setText("Value : ");

        valueSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                valueSliderStateChanged(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(0, 255, 0));
        btn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("ON");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(255, 0, 0));
        btn2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("OFF");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));

        viewStatusbtn.setBackground(new java.awt.Color(51, 255, 0));
        viewStatusbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewStatusbtn.setForeground(new java.awt.Color(255, 255, 255));
        viewStatusbtn.setText("VIEW STATUS");
        viewStatusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStatusbtnActionPerformed(evt);
            }
        });

        backtohomebtn.setBackground(new java.awt.Color(255, 0, 51));
        backtohomebtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backtohomebtn.setForeground(new java.awt.Color(255, 255, 255));
        backtohomebtn.setText("BACK");
        backtohomebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtohomebtnActionPerformed(evt);
            }
        });

        exitbtn.setBackground(new java.awt.Color(255, 0, 51));
        exitbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn.setText("EXIT");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(roomcbox, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(deviceCbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(valuelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(valueSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 143, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(backtohomebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewStatusbtn)
                .addGap(242, 242, 242))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(roomcbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(deviceCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valuelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewStatusbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backtohomebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomcboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomcboxActionPerformed
        // TODO add your handling code here:
        deviceCbox.removeAllItems();
        
        String room = roomcbox.getSelectedItem().toString();
        
        switch(room){
            case "Living Room":
                deviceCbox.addItem(controller.getLight(room).getName());
                deviceCbox.addItem(controller.getFan(room).getName());
                deviceCbox.addItem(controller.getTv(room).getName());
                deviceCbox.addItem(controller.getDoor(room).getName());
                break;
            case "Bedroom":
                deviceCbox.addItem(controller.getLight(room).getName());
                deviceCbox.addItem(controller.getFan(room).getName());
                deviceCbox.addItem(controller.getAc(room).getName());
                break;
            case "Kitchen":
                deviceCbox.addItem(controller.getLight(room).getName());
                deviceCbox.addItem(controller.getLight(room).getName());
                break;
            case "Office":
                deviceCbox.addItem(controller.getLight(room).getName());
                deviceCbox.addItem(controller.getFan(room).getName());
                deviceCbox.addItem(controller.getAc(room).getName());
                break;
        }
        
        
        
    }//GEN-LAST:event_roomcboxActionPerformed

    private void deviceCboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deviceCboxActionPerformed
        Object selected = deviceCbox.getSelectedItem();

    if(selected == null){
        return;
    }

    String device = selected.toString();

    switch(device){
        case "Light":
            valuelbl.setText("Brightness : " + valueSlider.getValue());
            valueSlider.setVisible(true);
            valueSlider.setMinimum(0);
            valueSlider.setMaximum(100);
            btn1.setText("ON");
            btn2.setText("OFF");
            break;

        case "Fan":
            valuelbl.setText("Speed : " + valueSlider.getValue());
            valueSlider.setVisible(true);
            valueSlider.setMinimum(0);
            valueSlider.setMaximum(5);
            btn1.setText("ON");
            btn2.setText("OFF");
            break;

        case "TV":
            valuelbl.setText("Volume : " + valueSlider.getValue());
            valueSlider.setVisible(true);
            valueSlider.setMinimum(0);
            valueSlider.setMaximum(100);
            btn1.setText("ON");
            btn2.setText("OFF");
            break;

        case "AC":
            valuelbl.setText("Temperature : " + valueSlider.getValue() + "°C");
            valueSlider.setVisible(true);
            valueSlider.setMinimum(16);
            valueSlider.setMaximum(30);
            btn1.setText("ON");
            btn2.setText("OFF");
            break;

        case "Door":
            valuelbl.setText("Status : ");

            valueSlider.setVisible(false);

            btn1.setText("UNLOCK");
            btn2.setText("LOCK");

            //lockedlbl.setText("Locked : ");
            break;
    }
    }//GEN-LAST:event_deviceCboxActionPerformed

    private void backtohomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtohomebtnActionPerformed
        // TODO add your handling code here:
        new HomePage(controller).setVisible(true);
        dispose();
    }//GEN-LAST:event_backtohomebtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    private void valueSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_valueSliderStateChanged
        // TODO add your handling code here:
        Object selected = deviceCbox.getSelectedItem();
        
        if(selected == null){
            return;
        }
        
        String device = selected.toString();
        String room = roomcbox.getSelectedItem().toString();
    
        switch(device){
            case "Light":
                controller.getLight(room).setBrightness(valueSlider.getValue());
                valuelbl.setText("Brightness : "+valueSlider.getValue());
                break;
            case "Fan":
                controller.getFan(room).setSpeed(valueSlider.getValue());
                valuelbl.setText("Speed : "+valueSlider.getValue());
                break;
            case "TV":
                controller.getTv(room).setVolume(valueSlider.getValue());
                valuelbl.setText("Volume : "+valueSlider.getValue());
                break;
            case "AC":
                controller.getAc(room).setTemperature(valueSlider.getValue());
                valuelbl.setText("Temperature : "+valueSlider.getValue());
                break;
            
        }
    }//GEN-LAST:event_valueSliderStateChanged

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
         Object selected = deviceCbox.getSelectedItem();
        
        if(selected == null){
            return;
        }
        
        String device = selected.toString();
        String room = roomcbox.getSelectedItem().toString();
        
           switch(device){
            case "Light":
                controller.getLight(room).turnOn();
                valuelbl.setText("Brightness : "+valueSlider.getValue());
                //valuelbl.setText(valuelbl.getText()+"ON");
                break;
            case "Fan":
                controller.getFan(room).turnOn();
                //valuelbl.setText(valuelbl.getText()+"ON");
                break;
            case "TV":
                controller.getTv(room).turnOn();
                //valuelbl.setText(valuelbl.getText()+"ON");
                break;
            case "AC":
                controller.getAc(room).turnOn();
                //valuelbl.setText(valuelbl.getText()+"ON");
                break;
            case "Door":
                controller.getDoor(room).unlock();
                valuelbl.setText("Status : "+controller.getDoor(room).getLockStatus());
                //lockedlbl.setText(lockedlbl.getText()+"UNLOCK");
                break;
        }
        
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        Object selected = deviceCbox.getSelectedItem();
        
        if(selected == null){
            return;
        }
        
        String device = selected.toString();
        String room = roomcbox.getSelectedItem().toString();
        
           switch(device){
            case "Light":
                controller.getLight(room).turnOff();
                valuelbl.setText("Brightness : 0");
                break;
            case "Fan":
                controller.getFan(room).turnOff();
                break;
            case "TV":
                controller.getTv(room).turnOff();
                break;
            case "AC":
                controller.getAc(room).turnOff();
                break;
            case "Door":
                controller.getDoor(room).lock();
                valuelbl.setText("Status : "+controller.getDoor(room).getLockStatus());
                //lockedlbl.setText(lockedlbl.getText()+"LOCK");
                break;
        }
        
    }//GEN-LAST:event_btn2ActionPerformed

    private void viewStatusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStatusbtnActionPerformed
        // TODO add your handling code here:
        String room = roomcbox.getSelectedItem().toString();
        
        switch(room){
            case "Living Room":
                new LivingRoom(controller).setVisible(true);
                dispose();
                break;
            case "Bedroom":
                new Bedroom(controller).setVisible(true);
                dispose();
                break;
            case "Office":
                new Office(controller).setVisible(true);
                dispose();
                break;
             case "Kitchen":
                new Kitchen(controller).setVisible(true);
                dispose();
                break;
        }
        
        
    }//GEN-LAST:event_viewStatusbtnActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtohomebtn;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JComboBox<String> deviceCbox;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox<String> roomcbox;
    private javax.swing.JSlider valueSlider;
    private javax.swing.JLabel valuelbl;
    private javax.swing.JButton viewStatusbtn;
    // End of variables declaration//GEN-END:variables
}
