/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smarthomesystem;

/**
 *
 * @author User
 */
public class RoomsPage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public RoomsPage() {
        initComponents();
        setTitle("Rooms");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        headinglbl = new javax.swing.JLabel();
        logolbl = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        livingRoombtn = new javax.swing.JButton();
        bedRoombtn = new javax.swing.JButton();
        kitchenbtn = new javax.swing.JButton();
        officebtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftPanel.setBackground(new java.awt.Color(255, 255, 0));
        leftPanel.setPreferredSize(new java.awt.Dimension(590, 415));

        headinglbl.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        headinglbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headinglbl.setText("SMART HOME SYSTEM");

        logolbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smarthomesystem/logo (3).png"))); // NOI18N

        rightPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 204, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SELECT ROOM");
        jLabel2.setOpaque(true);

        livingRoombtn.setBackground(new java.awt.Color(255, 255, 0));
        livingRoombtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        livingRoombtn.setText("Living Room");
        livingRoombtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livingRoombtnActionPerformed(evt);
            }
        });

        bedRoombtn.setBackground(new java.awt.Color(255, 255, 0));
        bedRoombtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bedRoombtn.setText("Bedroom");
        bedRoombtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedRoombtnActionPerformed(evt);
            }
        });

        kitchenbtn.setBackground(new java.awt.Color(255, 255, 0));
        kitchenbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kitchenbtn.setText("Kitchen");
        kitchenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitchenbtnActionPerformed(evt);
            }
        });

        officebtn.setBackground(new java.awt.Color(255, 255, 0));
        officebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        officebtn.setText("Office");
        officebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officebtnActionPerformed(evt);
            }
        });

        exitbtn.setBackground(new java.awt.Color(255, 0, 0));
        exitbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn.setText("Exit");

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(livingRoombtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bedRoombtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kitchenbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(officebtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitbtn)
                .addGap(31, 31, 31))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(livingRoombtn)
                .addGap(18, 18, 18)
                .addComponent(bedRoombtn)
                .addGap(18, 18, 18)
                .addComponent(kitchenbtn)
                .addGap(18, 18, 18)
                .addComponent(officebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(exitbtn)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logolbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(headinglbl, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(49, 49, 49)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(headinglbl)
                .addGap(41, 41, 41)
                .addComponent(logolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void livingRoombtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livingRoombtnActionPerformed
        // TODO add your handling code here:
        new LivingRoom().setVisible(true);
    }//GEN-LAST:event_livingRoombtnActionPerformed

    private void bedRoombtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedRoombtnActionPerformed
        
        new Bedroom().setVisible(true);
    }//GEN-LAST:event_bedRoombtnActionPerformed

    private void kitchenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitchenbtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_kitchenbtnActionPerformed

    private void officebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officebtnActionPerformed
        // TODO add your handling code here:
        new Office().setVisible(true);
    }//GEN-LAST:event_officebtnActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bedRoombtn;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel headinglbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton kitchenbtn;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton livingRoombtn;
    private javax.swing.JLabel logolbl;
    private javax.swing.JButton officebtn;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
}
