/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smarthomesystem;

public class SmartHomeController extends javax.swing.JFrame {

    public SmartHomeController() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        devicelbl = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        valueControllersld = new javax.swing.JSlider();
        valuelbl = new javax.swing.JLabel();
        onbtn = new javax.swing.JButton();
        offbtn = new javax.swing.JButton();
        devicelbl1 = new javax.swing.JLabel();
        devicenamelbl = new javax.swing.JLabel();
        powerlbl = new javax.swing.JLabel();
        powerlbl1 = new javax.swing.JLabel();
        switchlbl = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        doorlbl = new javax.swing.JLabel();
        unlockbtn = new javax.swing.JButton();
        lockbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("SimSun", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SMART HOME CONTROLLER");
        jLabel1.setOpaque(true);

        devicelbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        devicelbl.setText("Select Device:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Living Room Light", "Bedroom Fan", "Living Room TV", "Bedroom AC", "Main Door" }));

        valueControllersld.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        valueControllersld.setOpaque(true);

        valuelbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        valuelbl.setText("Value:");

        onbtn.setBackground(new java.awt.Color(0, 204, 0));
        onbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        onbtn.setForeground(new java.awt.Color(255, 255, 255));
        onbtn.setText("ON");

        offbtn.setBackground(new java.awt.Color(255, 0, 0));
        offbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        offbtn.setForeground(new java.awt.Color(255, 255, 255));
        offbtn.setText("OFF");
        offbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offbtnActionPerformed(evt);
            }
        });

        devicelbl1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        devicelbl1.setText("Device Status");

        devicenamelbl.setText("Device Name :");

        powerlbl.setText("Power :");

        powerlbl1.setText("Value :");

        switchlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        switchlbl.setText("Switch:");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smarthomesystem/logo (3).png"))); // NOI18N

        doorlbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        doorlbl.setText("Door:");

        unlockbtn.setBackground(new java.awt.Color(0, 204, 0));
        unlockbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        unlockbtn.setForeground(new java.awt.Color(255, 255, 255));
        unlockbtn.setText("UNLOCK");
        unlockbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unlockbtnActionPerformed(evt);
            }
        });

        lockbtn.setBackground(new java.awt.Color(255, 0, 0));
        lockbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lockbtn.setForeground(new java.awt.Color(255, 255, 255));
        lockbtn.setText("LOCK");
        lockbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(devicelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valuelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(switchlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(doorlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valueControllersld, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                            .addComponent(onbtn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(offbtn))
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                            .addComponent(unlockbtn)
                                            .addGap(18, 18, 18)
                                            .addComponent(lockbtn)))))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(devicelbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(devicenamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(powerlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(powerlbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(devicelbl)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valuelbl)
                            .addComponent(valueControllersld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(switchlbl)
                            .addComponent(onbtn)
                            .addComponent(offbtn))
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unlockbtn)
                            .addComponent(lockbtn)
                            .addComponent(doorlbl))
                        .addGap(27, 27, 27)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(devicelbl1)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(devicenamelbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(powerlbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(powerlbl1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void offbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_offbtnActionPerformed

    private void lockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lockbtnActionPerformed

    private void unlockbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unlockbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unlockbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartHomeController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartHomeController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartHomeController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartHomeController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmartHomeController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel devicelbl;
    private javax.swing.JLabel devicelbl1;
    private javax.swing.JLabel devicenamelbl;
    private javax.swing.JLabel doorlbl;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lockbtn;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton offbtn;
    private javax.swing.JButton onbtn;
    private javax.swing.JLabel powerlbl;
    private javax.swing.JLabel powerlbl1;
    private javax.swing.JLabel switchlbl;
    private javax.swing.JButton unlockbtn;
    private javax.swing.JSlider valueControllersld;
    private javax.swing.JLabel valuelbl;
    // End of variables declaration//GEN-END:variables
}
